name: UWP CI

on:
  push:
    paths:
      - "UWP/**"

jobs:
  build:
    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v1
      - name: Setup Nuget.exe
        uses: warrenbuckley/Setup-Nuget@v1
      - name: Setup MSBuild.exe
        uses: warrenbuckley/Setup-MSBuild@v1
      - name: Restore with nuget
        working-directory: ./UWP
        run: nuget restore ./WeiPo.sln
      - name: Build with msbuild
        working-directory: ./UWP
        run: msbuild ./WeiPo.sln /m /verbosity:detailed /p:Configuration=Release /p:AppxBundle=Always /p:AppxBundlePlatforms="ARM|x86|x64" /p:UapAppxPackageBuildMode=StoreUpload
